<?php

namespace Modules\Settings\Services;

use Illuminate\Support\Facades\DB;
use Modules\Settings\Models\SystemSetting;

/**
 * Real database backup / restore.
 *
 * Dumps every table of the configured MySQL database to a .sql file under
 * storage/app/backups using PDO (no mysqldump binary required), and records
 * each backup entry in system_settings.backups so the portal's Backup &
 * Restore card reflects the true state of the database.
 */
class BackupService
{
    /** Directory where .sql dump files are stored. */
    public static function directory(): string
    {
        $dir = storage_path('app/backups');

        if (! is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        return $dir;
    }

    /**
     * All stored backup entries (newest first).
     *
     * @return array<int, array{id: string, timestamp: string, size: string, type: string, filename: string}>
     */
    public static function entries(): array
    {
        $entries = SystemSetting::getValue('backups', []);

        return is_array($entries) ? array_values($entries) : [];
    }

    public static function findEntry(string $id): ?array
    {
        foreach (static::entries() as $entry) {
            if (($entry['id'] ?? null) === $id) {
                return $entry;
            }
        }

        return null;
    }

    /**
     * Dump the whole database and record the entry in system_settings.
     *
     * @return array The created backup entry.
     *
     * @throws \RuntimeException when the dump fails.
     */
    public static function create(string $type = 'Manual'): array
    {
        $pdo = DB::connection()->getPdo();

        $nextNumber = count(static::entries()) + 1;
        do {
            $id = 'BKP-' . $nextNumber;
            $filename = $id . '-' . now()->format('Ymd-His') . '.sql';
            $nextNumber++;
        } while (static::findEntry($id) !== null);

        $path = static::directory() . DIRECTORY_SEPARATOR . $filename;

        try {
            $sql = static::generateDump($pdo);
            file_put_contents($path, $sql);
        } catch (\Throwable $e) {
            @unlink($path);
            throw new \RuntimeException('Backup failed: ' . $e->getMessage(), 0, $e);
        }

        $entry = [
            'id'        => $id,
            'timestamp' => now()->format('Y-m-d H:i'),
            'size'      => static::humanSize(filesize($path) ?: 0),
            'type'      => $type,
            'filename'  => $filename,
        ];

        // Newest entry first — matches how the frontend renders the table.
        $entries = static::entries();
        array_unshift($entries, $entry);
        SystemSetting::setValue('backups', $entries);

        return $entry;
    }

    /**
     * Restore the database from a previously created dump file.
     *
     * @throws \RuntimeException when the entry/file is missing or a statement fails.
     */
    public static function restore(string $id): int
    {
        $entry = static::findEntry($id);

        if (! $entry) {
            throw new \RuntimeException("Backup '{$id}' was not found.");
        }

        $path = static::directory() . DIRECTORY_SEPARATOR . ($entry['filename'] ?? '');

        if (! is_file($path)) {
            throw new \RuntimeException("Backup file for '{$id}' is missing on the server.");
        }

        $pdo = DB::connection()->getPdo();
        $contents = (string) file_get_contents($path);

        // Files are generated by us with one statement per line, so ";\n"
        // is a safe statement delimiter.
        $statements = explode(";\n", $contents);

        // Keep the backup catalog — snapshots don't contain their own entry,
        // and restoring shouldn't wipe the history of existing .sql files.
        $catalog = static::entries();

        $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
        $pdo->exec('SET UNIQUE_CHECKS=0');
        $pdo->exec("SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO'");

        $executed = 0;
        try {
            foreach ($statements as $statement) {
                // Drop full-line comment lines, then run whatever remains.
                $statement = trim((string) preg_replace('/^--.*$/m', '', $statement));

                if ($statement === '') {
                    continue;
                }

                $pdo->exec($statement);
                $executed++;
            }
        } catch (\Throwable $e) {
            throw new \RuntimeException('Restore failed: ' . $e->getMessage(), 0, $e);
        } finally {
            $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
            $pdo->exec('SET UNIQUE_CHECKS=1');

            SystemSetting::setValue('backups', $catalog);
        }

        return $executed;
    }

    /* ------------------------------------------------------------------ */
    /* Internals                                                            */
    /* ------------------------------------------------------------------ */

    private static function generateDump(\PDO $pdo): string
    {
        $database = DB::connection()->getDatabaseName();

        $out = "-- Database backup\n";
        $out .= '-- Generated: ' . now()->format('Y-m-d H:i:s') . "\n";
        $out .= '-- Database: ' . $database . "\n\n";
        $out .= "SET NAMES utf8mb4;\n";
        $out .= "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n";
        $out .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        $tables = $pdo
            ->query('SHOW FULL TABLES WHERE Table_type = \'BASE TABLE\'')
            ->fetchAll(\PDO::FETCH_COLUMN);

        foreach ($tables as $table) {
            $create = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(\PDO::FETCH_NUM);

            $out .= "-- Table: {$table}\n";
            $out .= "DROP TABLE IF EXISTS `{$table}`;\n";
            $out .= $create[1] . ";\n\n";

            $rows = $pdo->query("SELECT * FROM `{$table}`")->fetchAll(\PDO::FETCH_ASSOC);

            if ($rows === []) {
                continue;
            }

            $columns = '`' . implode('`, `', array_keys($rows[0])) . '`';

            foreach (array_chunk($rows, 100) as $chunk) {
                $values = [];

                foreach ($chunk as $row) {
                    $escaped = implode(', ', array_map(
                        fn ($v) => static::quoteValue($v),
                        array_values($row),
                    ));
                    $values[] = "({$escaped})";
                }

                $out .= "INSERT INTO `{$table}` ({$columns}) VALUES\n"
                    . implode(",\n", $values) . ";\n";
            }

            $out .= "\n";
        }

        $out .= "SET FOREIGN_KEY_CHECKS=1;\n";

        return $out;
    }

    /** SQL-escapes a value; newlines are encoded so one statement stays on one line. */
    private static function quoteValue(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        $escaped = str_replace(
            ['\\', "\0", "\n", "\r", "\x1A", "'"],
            ['\\\\', '\\0', '\\n', '\\r', '\\Z', "\\'"],
            (string) $value,
        );

        return "'{$escaped}'";
    }

    private static function humanSize(int|float $bytes): string
    {
        if ($bytes >= 1048576) {
            return round($bytes / 1048576, 1) . ' MB';
        }
        if ($bytes >= 1024) {
            return round($bytes / 1024, 1) . ' KB';
        }

        return $bytes . ' B';
    }
}
