/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as LandingContactRouteImport } from './routes/_landing/contact'
import { Route as LandingFaqRouteImport } from './routes/_landing/faq'
import { Route as LoginForgotPasswordRouteImport } from './routes/_login/forgot-password'
import { Route as LoginLoginRouteImport } from './routes/_login/login'
import { Route as LoginOtpRouteImport } from './routes/_login/otp'
import { Route as LoginResetPasswordRouteImport } from './routes/_login/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as EmployeeAiRouteImport } from './routes/employee/ai'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as LandingJobsIndexRouteImport } from './routes/_landing/jobs.index'
import { Route as LandingJobsJobIdRouteImport } from './routes/_landing/jobs.$jobId'
import { Route as AdminApplicantManagementApplicantsRouteImport } from './routes/admin/_applicant-management/applicants'
import { Route as AdminCorehcmDeptPosRouteImport } from './routes/admin/_corehcm/dept-pos'
import { Route as AdminCorehcmHcmRouteImport } from './routes/admin/_corehcm/hcm'
import { Route as AdminCorehcmOrgChartRouteImport } from './routes/admin/_corehcm/org-chart'
import { Route as AdminEmployeerecordsEmployeesRouteImport } from './routes/admin/_employeerecords/employees'
import { Route as AdminEssmanagementEssRouteImport } from './routes/admin/_essmanagement/ess'
import { Route as AdminNewhireonboardingOnboardingRouteImport } from './routes/admin/_newhireonboarding/onboarding'
import { Route as AdminProfilepageProfileRouteImport } from './routes/admin/_profilepage/profile'
import { Route as AdminRecruitmentmanagementRecruitmentRouteImport } from './routes/admin/_recruitmentmanagement/recruitment'
import { Route as AdminSettingsChatbotRouteImport } from './routes/admin/_settings/chatbot'
import { Route as AdminSettingsSettingsRouteImport } from './routes/admin/_settings/settings'
import { Route as EmployeeEssmanagementEssRouteImport } from './routes/employee/_essmanagement/ess'
import { Route as EmployeeNewhireonboardingOnboardingRouteImport } from './routes/employee/_newhireonboarding/onboarding'
import { Route as EmployeeProfilepageProfileRouteImport } from './routes/employee/_profilepage/profile'
import { Route as EmployeeSettingsSettingsRouteImport } from './routes/employee/_settings/settings'
import { Route as SuperadminApplicantManagementApplicantsRouteImport } from './routes/superadmin/_applicant-management/applicants'
import { Route as SuperadminAuditlogsAuditRouteImport } from './routes/superadmin/_auditlogs/audit'
import { Route as SuperadminCorehcmDeptPosRouteImport } from './routes/superadmin/_corehcm/dept-pos'
import { Route as SuperadminCorehcmHcmRouteImport } from './routes/superadmin/_corehcm/hcm'
import { Route as SuperadminCorehcmOrgChartRouteImport } from './routes/superadmin/_corehcm/org-chart'
import { Route as SuperadminEmployeerecordsEmployeesRouteImport } from './routes/superadmin/_employeerecords/employees'
import { Route as SuperadminEssmanagementEssRouteImport } from './routes/superadmin/_essmanagement/ess'
import { Route as SuperadminNewhireonboardingOnboardingRouteImport } from './routes/superadmin/_newhireonboarding/onboarding'
import { Route as SuperadminProfilepageProfileRouteImport } from './routes/superadmin/_profilepage/profile'
import { Route as SuperadminRecruitmentmanagementRecruitmentRouteImport } from './routes/superadmin/_recruitmentmanagement/recruitment'
import { Route as SuperadminSettingsChatbotRouteImport } from './routes/superadmin/_settings/chatbot'
import { Route as SuperadminSettingsSettingsRouteImport } from './routes/superadmin/_settings/settings'
import { Route as SuperadminUsermanagementUsersRouteImport } from './routes/superadmin/_usermanagement/users'

const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/_landing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/_landing/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingContactRoute = LandingContactRouteImport.update({
  id: '/_landing/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingFaqRoute = LandingFaqRouteImport.update({
  id: '/_landing/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/_login/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/_login/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/_login/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/_login/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAiRoute = EmployeeAiRouteImport.update({
  id: '/employee/ai',
  path: '/employee/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingJobsIndexRoute = LandingJobsIndexRouteImport.update({
  id: '/_landing/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingJobsJobIdRoute = LandingJobsJobIdRouteImport.update({
  id: '/_landing/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicantManagementApplicantsRoute =
  AdminApplicantManagementApplicantsRouteImport.update({
    id: '/admin/_applicant-management/applicants',
    path: '/admin/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCorehcmDeptPosRoute = AdminCorehcmDeptPosRouteImport.update({
  id: '/admin/_corehcm/dept-pos',
  path: '/admin/dept-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorehcmHcmRoute = AdminCorehcmHcmRouteImport.update({
  id: '/admin/_corehcm/hcm',
  path: '/admin/hcm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorehcmOrgChartRoute = AdminCorehcmOrgChartRouteImport.update({
  id: '/admin/_corehcm/org-chart',
  path: '/admin/org-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeerecordsEmployeesRoute =
  AdminEmployeerecordsEmployeesRouteImport.update({
    id: '/admin/_employeerecords/employees',
    path: '/admin/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEssmanagementEssRoute = AdminEssmanagementEssRouteImport.update({
  id: '/admin/_essmanagement/ess',
  path: '/admin/ess',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewhireonboardingOnboardingRoute =
  AdminNewhireonboardingOnboardingRouteImport.update({
    id: '/admin/_newhireonboarding/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProfilepageProfileRoute = AdminProfilepageProfileRouteImport.update({
  id: '/admin/_profilepage/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentmanagementRecruitmentRoute =
  AdminRecruitmentmanagementRecruitmentRouteImport.update({
    id: '/admin/_recruitmentmanagement/recruitment',
    path: '/admin/recruitment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsChatbotRoute = AdminSettingsChatbotRouteImport.update({
  id: '/admin/_settings/chatbot',
  path: '/admin/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSettingsRoute = AdminSettingsSettingsRouteImport.update({
  id: '/admin/_settings/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEssmanagementEssRoute =
  EmployeeEssmanagementEssRouteImport.update({
    id: '/employee/_essmanagement/ess',
    path: '/employee/ess',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeNewhireonboardingOnboardingRoute =
  EmployeeNewhireonboardingOnboardingRouteImport.update({
    id: '/employee/_newhireonboarding/onboarding',
    path: '/employee/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeProfilepageProfileRoute =
  EmployeeProfilepageProfileRouteImport.update({
    id: '/employee/_profilepage/profile',
    path: '/employee/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeSettingsSettingsRoute =
  EmployeeSettingsSettingsRouteImport.update({
    id: '/employee/_settings/settings',
    path: '/employee/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminApplicantManagementApplicantsRoute =
  SuperadminApplicantManagementApplicantsRouteImport.update({
    id: '/superadmin/_applicant-management/applicants',
    path: '/superadmin/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminAuditlogsAuditRoute =
  SuperadminAuditlogsAuditRouteImport.update({
    id: '/superadmin/_auditlogs/audit',
    path: '/superadmin/audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminCorehcmDeptPosRoute =
  SuperadminCorehcmDeptPosRouteImport.update({
    id: '/superadmin/_corehcm/dept-pos',
    path: '/superadmin/dept-pos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminCorehcmHcmRoute = SuperadminCorehcmHcmRouteImport.update({
  id: '/superadmin/_corehcm/hcm',
  path: '/superadmin/hcm',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminCorehcmOrgChartRoute =
  SuperadminCorehcmOrgChartRouteImport.update({
    id: '/superadmin/_corehcm/org-chart',
    path: '/superadmin/org-chart',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminEmployeerecordsEmployeesRoute =
  SuperadminEmployeerecordsEmployeesRouteImport.update({
    id: '/superadmin/_employeerecords/employees',
    path: '/superadmin/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminEssmanagementEssRoute =
  SuperadminEssmanagementEssRouteImport.update({
    id: '/superadmin/_essmanagement/ess',
    path: '/superadmin/ess',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminNewhireonboardingOnboardingRoute =
  SuperadminNewhireonboardingOnboardingRouteImport.update({
    id: '/superadmin/_newhireonboarding/onboarding',
    path: '/superadmin/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminProfilepageProfileRoute =
  SuperadminProfilepageProfileRouteImport.update({
    id: '/superadmin/_profilepage/profile',
    path: '/superadmin/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminRecruitmentmanagementRecruitmentRoute =
  SuperadminRecruitmentmanagementRecruitmentRouteImport.update({
    id: '/superadmin/_recruitmentmanagement/recruitment',
    path: '/superadmin/recruitment',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminSettingsChatbotRoute =
  SuperadminSettingsChatbotRouteImport.update({
    id: '/superadmin/_settings/chatbot',
    path: '/superadmin/chatbot',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminSettingsSettingsRoute =
  SuperadminSettingsSettingsRouteImport.update({
    id: '/superadmin/_settings/settings',
    path: '/superadmin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminUsermanagementUsersRoute =
  SuperadminUsermanagementUsersRouteImport.update({
    id: '/superadmin/_usermanagement/users',
    path: '/superadmin/users',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/faq': typeof LandingFaqRoute
  '/forgot-password': typeof LoginForgotPasswordRoute
  '/login': typeof LoginLoginRoute
  '/otp': typeof LoginOtpRoute
  '/reset-password': typeof LoginResetPasswordRoute
  '/employee/ai': typeof EmployeeAiRoute
  '/': typeof LandingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/jobs/$jobId': typeof LandingJobsJobIdRoute
  '/admin/applicants': typeof AdminApplicantManagementApplicantsRoute
  '/admin/dept-pos': typeof AdminCorehcmDeptPosRoute
  '/admin/hcm': typeof AdminCorehcmHcmRoute
  '/admin/org-chart': typeof AdminCorehcmOrgChartRoute
  '/admin/employees': typeof AdminEmployeerecordsEmployeesRoute
  '/admin/ess': typeof AdminEssmanagementEssRoute
  '/admin/onboarding': typeof AdminNewhireonboardingOnboardingRoute
  '/admin/profile': typeof AdminProfilepageProfileRoute
  '/admin/recruitment': typeof AdminRecruitmentmanagementRecruitmentRoute
  '/admin/chatbot': typeof AdminSettingsChatbotRoute
  '/admin/settings': typeof AdminSettingsSettingsRoute
  '/employee/ess': typeof EmployeeEssmanagementEssRoute
  '/employee/onboarding': typeof EmployeeNewhireonboardingOnboardingRoute
  '/employee/profile': typeof EmployeeProfilepageProfileRoute
  '/employee/settings': typeof EmployeeSettingsSettingsRoute
  '/superadmin/applicants': typeof SuperadminApplicantManagementApplicantsRoute
  '/superadmin/audit': typeof SuperadminAuditlogsAuditRoute
  '/superadmin/dept-pos': typeof SuperadminCorehcmDeptPosRoute
  '/superadmin/hcm': typeof SuperadminCorehcmHcmRoute
  '/superadmin/org-chart': typeof SuperadminCorehcmOrgChartRoute
  '/superadmin/employees': typeof SuperadminEmployeerecordsEmployeesRoute
  '/superadmin/ess': typeof SuperadminEssmanagementEssRoute
  '/superadmin/onboarding': typeof SuperadminNewhireonboardingOnboardingRoute
  '/superadmin/profile': typeof SuperadminProfilepageProfileRoute
  '/superadmin/recruitment': typeof SuperadminRecruitmentmanagementRecruitmentRoute
  '/superadmin/chatbot': typeof SuperadminSettingsChatbotRoute
  '/superadmin/settings': typeof SuperadminSettingsSettingsRoute
  '/superadmin/users': typeof SuperadminUsermanagementUsersRoute
  '/jobs/': typeof LandingJobsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/faq': typeof LandingFaqRoute
  '/forgot-password': typeof LoginForgotPasswordRoute
  '/login': typeof LoginLoginRoute
  '/otp': typeof LoginOtpRoute
  '/reset-password': typeof LoginResetPasswordRoute
  '/employee/ai': typeof EmployeeAiRoute
  '/': typeof LandingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/jobs/$jobId': typeof LandingJobsJobIdRoute
  '/admin/applicants': typeof AdminApplicantManagementApplicantsRoute
  '/admin/dept-pos': typeof AdminCorehcmDeptPosRoute
  '/admin/hcm': typeof AdminCorehcmHcmRoute
  '/admin/org-chart': typeof AdminCorehcmOrgChartRoute
  '/admin/employees': typeof AdminEmployeerecordsEmployeesRoute
  '/admin/ess': typeof AdminEssmanagementEssRoute
  '/admin/onboarding': typeof AdminNewhireonboardingOnboardingRoute
  '/admin/profile': typeof AdminProfilepageProfileRoute
  '/admin/recruitment': typeof AdminRecruitmentmanagementRecruitmentRoute
  '/admin/chatbot': typeof AdminSettingsChatbotRoute
  '/admin/settings': typeof AdminSettingsSettingsRoute
  '/employee/ess': typeof EmployeeEssmanagementEssRoute
  '/employee/onboarding': typeof EmployeeNewhireonboardingOnboardingRoute
  '/employee/profile': typeof EmployeeProfilepageProfileRoute
  '/employee/settings': typeof EmployeeSettingsSettingsRoute
  '/superadmin/applicants': typeof SuperadminApplicantManagementApplicantsRoute
  '/superadmin/audit': typeof SuperadminAuditlogsAuditRoute
  '/superadmin/dept-pos': typeof SuperadminCorehcmDeptPosRoute
  '/superadmin/hcm': typeof SuperadminCorehcmHcmRoute
  '/superadmin/org-chart': typeof SuperadminCorehcmOrgChartRoute
  '/superadmin/employees': typeof SuperadminEmployeerecordsEmployeesRoute
  '/superadmin/ess': typeof SuperadminEssmanagementEssRoute
  '/superadmin/onboarding': typeof SuperadminNewhireonboardingOnboardingRoute
  '/superadmin/profile': typeof SuperadminProfilepageProfileRoute
  '/superadmin/recruitment': typeof SuperadminRecruitmentmanagementRecruitmentRoute
  '/superadmin/chatbot': typeof SuperadminSettingsChatbotRoute
  '/superadmin/settings': typeof SuperadminSettingsSettingsRoute
  '/superadmin/users': typeof SuperadminUsermanagementUsersRoute
  '/jobs': typeof LandingJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/contact': typeof LandingContactRoute
  '/_landing/faq': typeof LandingFaqRoute
  '/_login/forgot-password': typeof LoginForgotPasswordRoute
  '/_login/login': typeof LoginLoginRoute
  '/_login/otp': typeof LoginOtpRoute
  '/_login/reset-password': typeof LoginResetPasswordRoute
  '/employee/ai': typeof EmployeeAiRoute
  '/_landing/': typeof LandingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/_landing/jobs/$jobId': typeof LandingJobsJobIdRoute
  '/admin/_applicant-management/applicants': typeof AdminApplicantManagementApplicantsRoute
  '/admin/_corehcm/dept-pos': typeof AdminCorehcmDeptPosRoute
  '/admin/_corehcm/hcm': typeof AdminCorehcmHcmRoute
  '/admin/_corehcm/org-chart': typeof AdminCorehcmOrgChartRoute
  '/admin/_employeerecords/employees': typeof AdminEmployeerecordsEmployeesRoute
  '/admin/_essmanagement/ess': typeof AdminEssmanagementEssRoute
  '/admin/_newhireonboarding/onboarding': typeof AdminNewhireonboardingOnboardingRoute
  '/admin/_profilepage/profile': typeof AdminProfilepageProfileRoute
  '/admin/_recruitmentmanagement/recruitment': typeof AdminRecruitmentmanagementRecruitmentRoute
  '/admin/_settings/chatbot': typeof AdminSettingsChatbotRoute
  '/admin/_settings/settings': typeof AdminSettingsSettingsRoute
  '/employee/_essmanagement/ess': typeof EmployeeEssmanagementEssRoute
  '/employee/_newhireonboarding/onboarding': typeof EmployeeNewhireonboardingOnboardingRoute
  '/employee/_profilepage/profile': typeof EmployeeProfilepageProfileRoute
  '/employee/_settings/settings': typeof EmployeeSettingsSettingsRoute
  '/superadmin/_applicant-management/applicants': typeof SuperadminApplicantManagementApplicantsRoute
  '/superadmin/_auditlogs/audit': typeof SuperadminAuditlogsAuditRoute
  '/superadmin/_corehcm/dept-pos': typeof SuperadminCorehcmDeptPosRoute
  '/superadmin/_corehcm/hcm': typeof SuperadminCorehcmHcmRoute
  '/superadmin/_corehcm/org-chart': typeof SuperadminCorehcmOrgChartRoute
  '/superadmin/_employeerecords/employees': typeof SuperadminEmployeerecordsEmployeesRoute
  '/superadmin/_essmanagement/ess': typeof SuperadminEssmanagementEssRoute
  '/superadmin/_newhireonboarding/onboarding': typeof SuperadminNewhireonboardingOnboardingRoute
  '/superadmin/_profilepage/profile': typeof SuperadminProfilepageProfileRoute
  '/superadmin/_recruitmentmanagement/recruitment': typeof SuperadminRecruitmentmanagementRecruitmentRoute
  '/superadmin/_settings/chatbot': typeof SuperadminSettingsChatbotRoute
  '/superadmin/_settings/settings': typeof SuperadminSettingsSettingsRoute
  '/superadmin/_usermanagement/users': typeof SuperadminUsermanagementUsersRoute
  '/_landing/jobs/': typeof LandingJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/reset-password'
    | '/employee/ai'
    | '/'
    | '/admin/'
    | '/employee/'
    | '/superadmin/'
    | '/jobs/$jobId'
    | '/admin/applicants'
    | '/admin/dept-pos'
    | '/admin/hcm'
    | '/admin/org-chart'
    | '/admin/employees'
    | '/admin/ess'
    | '/admin/onboarding'
    | '/admin/profile'
    | '/admin/recruitment'
    | '/admin/chatbot'
    | '/admin/settings'
    | '/employee/ess'
    | '/employee/onboarding'
    | '/employee/profile'
    | '/employee/settings'
    | '/superadmin/applicants'
    | '/superadmin/audit'
    | '/superadmin/dept-pos'
    | '/superadmin/hcm'
    | '/superadmin/org-chart'
    | '/superadmin/employees'
    | '/superadmin/ess'
    | '/superadmin/onboarding'
    | '/superadmin/profile'
    | '/superadmin/recruitment'
    | '/superadmin/chatbot'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/reset-password'
    | '/employee/ai'
    | '/'
    | '/admin'
    | '/employee'
    | '/superadmin'
    | '/jobs/$jobId'
    | '/admin/applicants'
    | '/admin/dept-pos'
    | '/admin/hcm'
    | '/admin/org-chart'
    | '/admin/employees'
    | '/admin/ess'
    | '/admin/onboarding'
    | '/admin/profile'
    | '/admin/recruitment'
    | '/admin/chatbot'
    | '/admin/settings'
    | '/employee/ess'
    | '/employee/onboarding'
    | '/employee/profile'
    | '/employee/settings'
    | '/superadmin/applicants'
    | '/superadmin/audit'
    | '/superadmin/dept-pos'
    | '/superadmin/hcm'
    | '/superadmin/org-chart'
    | '/superadmin/employees'
    | '/superadmin/ess'
    | '/superadmin/onboarding'
    | '/superadmin/profile'
    | '/superadmin/recruitment'
    | '/superadmin/chatbot'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/jobs'
  id:
    | '__root__'
    | '/_landing/about'
    | '/_landing/contact'
    | '/_landing/faq'
    | '/_login/forgot-password'
    | '/_login/login'
    | '/_login/otp'
    | '/_login/reset-password'
    | '/employee/ai'
    | '/_landing/'
    | '/admin/'
    | '/employee/'
    | '/superadmin/'
    | '/_landing/jobs/$jobId'
    | '/admin/_applicant-management/applicants'
    | '/admin/_corehcm/dept-pos'
    | '/admin/_corehcm/hcm'
    | '/admin/_corehcm/org-chart'
    | '/admin/_employeerecords/employees'
    | '/admin/_essmanagement/ess'
    | '/admin/_newhireonboarding/onboarding'
    | '/admin/_profilepage/profile'
    | '/admin/_recruitmentmanagement/recruitment'
    | '/admin/_settings/chatbot'
    | '/admin/_settings/settings'
    | '/employee/_essmanagement/ess'
    | '/employee/_newhireonboarding/onboarding'
    | '/employee/_profilepage/profile'
    | '/employee/_settings/settings'
    | '/superadmin/_applicant-management/applicants'
    | '/superadmin/_auditlogs/audit'
    | '/superadmin/_corehcm/dept-pos'
    | '/superadmin/_corehcm/hcm'
    | '/superadmin/_corehcm/org-chart'
    | '/superadmin/_employeerecords/employees'
    | '/superadmin/_essmanagement/ess'
    | '/superadmin/_newhireonboarding/onboarding'
    | '/superadmin/_profilepage/profile'
    | '/superadmin/_recruitmentmanagement/recruitment'
    | '/superadmin/_settings/chatbot'
    | '/superadmin/_settings/settings'
    | '/superadmin/_usermanagement/users'
    | '/_landing/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingContactRoute: typeof LandingContactRoute
  LandingFaqRoute: typeof LandingFaqRoute
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  LoginLoginRoute: typeof LoginLoginRoute
  LoginOtpRoute: typeof LoginOtpRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  EmployeeAiRoute: typeof EmployeeAiRoute
  LandingIndexRoute: typeof LandingIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  LandingJobsJobIdRoute: typeof LandingJobsJobIdRoute
  AdminApplicantManagementApplicantsRoute: typeof AdminApplicantManagementApplicantsRoute
  AdminCorehcmDeptPosRoute: typeof AdminCorehcmDeptPosRoute
  AdminCorehcmHcmRoute: typeof AdminCorehcmHcmRoute
  AdminCorehcmOrgChartRoute: typeof AdminCorehcmOrgChartRoute
  AdminEmployeerecordsEmployeesRoute: typeof AdminEmployeerecordsEmployeesRoute
  AdminEssmanagementEssRoute: typeof AdminEssmanagementEssRoute
  AdminNewhireonboardingOnboardingRoute: typeof AdminNewhireonboardingOnboardingRoute
  AdminProfilepageProfileRoute: typeof AdminProfilepageProfileRoute
  AdminRecruitmentmanagementRecruitmentRoute: typeof AdminRecruitmentmanagementRecruitmentRoute
  AdminSettingsChatbotRoute: typeof AdminSettingsChatbotRoute
  AdminSettingsSettingsRoute: typeof AdminSettingsSettingsRoute
  EmployeeEssmanagementEssRoute: typeof EmployeeEssmanagementEssRoute
  EmployeeNewhireonboardingOnboardingRoute: typeof EmployeeNewhireonboardingOnboardingRoute
  EmployeeProfilepageProfileRoute: typeof EmployeeProfilepageProfileRoute
  EmployeeSettingsSettingsRoute: typeof EmployeeSettingsSettingsRoute
  SuperadminApplicantManagementApplicantsRoute: typeof SuperadminApplicantManagementApplicantsRoute
  SuperadminAuditlogsAuditRoute: typeof SuperadminAuditlogsAuditRoute
  SuperadminCorehcmDeptPosRoute: typeof SuperadminCorehcmDeptPosRoute
  SuperadminCorehcmHcmRoute: typeof SuperadminCorehcmHcmRoute
  SuperadminCorehcmOrgChartRoute: typeof SuperadminCorehcmOrgChartRoute
  SuperadminEmployeerecordsEmployeesRoute: typeof SuperadminEmployeerecordsEmployeesRoute
  SuperadminEssmanagementEssRoute: typeof SuperadminEssmanagementEssRoute
  SuperadminNewhireonboardingOnboardingRoute: typeof SuperadminNewhireonboardingOnboardingRoute
  SuperadminProfilepageProfileRoute: typeof SuperadminProfilepageProfileRoute
  SuperadminRecruitmentmanagementRecruitmentRoute: typeof SuperadminRecruitmentmanagementRecruitmentRoute
  SuperadminSettingsChatbotRoute: typeof SuperadminSettingsChatbotRoute
  SuperadminSettingsSettingsRoute: typeof SuperadminSettingsSettingsRoute
  SuperadminUsermanagementUsersRoute: typeof SuperadminUsermanagementUsersRoute
  LandingJobsIndexRoute: typeof LandingJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/faq': {
      id: '/_landing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LandingFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/forgot-password': {
      id: '/_login/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/otp': {
      id: '/_login/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/reset-password': {
      id: '/_login/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/ai': {
      id: '/employee/ai'
      path: '/employee/ai'
      fullPath: '/employee/ai'
      preLoaderRoute: typeof EmployeeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/jobs/': {
      id: '/_landing/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof LandingJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/jobs/$jobId': {
      id: '/_landing/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof LandingJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_applicant-management/applicants': {
      id: '/admin/_applicant-management/applicants'
      path: '/admin/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminApplicantManagementApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_corehcm/dept-pos': {
      id: '/admin/_corehcm/dept-pos'
      path: '/admin/dept-pos'
      fullPath: '/admin/dept-pos'
      preLoaderRoute: typeof AdminCorehcmDeptPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_corehcm/hcm': {
      id: '/admin/_corehcm/hcm'
      path: '/admin/hcm'
      fullPath: '/admin/hcm'
      preLoaderRoute: typeof AdminCorehcmHcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_corehcm/org-chart': {
      id: '/admin/_corehcm/org-chart'
      path: '/admin/org-chart'
      fullPath: '/admin/org-chart'
      preLoaderRoute: typeof AdminCorehcmOrgChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_employeerecords/employees': {
      id: '/admin/_employeerecords/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeerecordsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_essmanagement/ess': {
      id: '/admin/_essmanagement/ess'
      path: '/admin/ess'
      fullPath: '/admin/ess'
      preLoaderRoute: typeof AdminEssmanagementEssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_newhireonboarding/onboarding': {
      id: '/admin/_newhireonboarding/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminNewhireonboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_profilepage/profile': {
      id: '/admin/_profilepage/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfilepageProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_recruitmentmanagement/recruitment': {
      id: '/admin/_recruitmentmanagement/recruitment'
      path: '/admin/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentmanagementRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_settings/chatbot': {
      id: '/admin/_settings/chatbot'
      path: '/admin/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminSettingsChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_settings/settings': {
      id: '/admin/_settings/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/_essmanagement/ess': {
      id: '/employee/_essmanagement/ess'
      path: '/employee/ess'
      fullPath: '/employee/ess'
      preLoaderRoute: typeof EmployeeEssmanagementEssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/_newhireonboarding/onboarding': {
      id: '/employee/_newhireonboarding/onboarding'
      path: '/employee/onboarding'
      fullPath: '/employee/onboarding'
      preLoaderRoute: typeof EmployeeNewhireonboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/_profilepage/profile': {
      id: '/employee/_profilepage/profile'
      path: '/employee/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfilepageProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/_settings/settings': {
      id: '/employee/_settings/settings'
      path: '/employee/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_applicant-management/applicants': {
      id: '/superadmin/_applicant-management/applicants'
      path: '/superadmin/applicants'
      fullPath: '/superadmin/applicants'
      preLoaderRoute: typeof SuperadminApplicantManagementApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_auditlogs/audit': {
      id: '/superadmin/_auditlogs/audit'
      path: '/superadmin/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof SuperadminAuditlogsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_corehcm/dept-pos': {
      id: '/superadmin/_corehcm/dept-pos'
      path: '/superadmin/dept-pos'
      fullPath: '/superadmin/dept-pos'
      preLoaderRoute: typeof SuperadminCorehcmDeptPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_corehcm/hcm': {
      id: '/superadmin/_corehcm/hcm'
      path: '/superadmin/hcm'
      fullPath: '/superadmin/hcm'
      preLoaderRoute: typeof SuperadminCorehcmHcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_corehcm/org-chart': {
      id: '/superadmin/_corehcm/org-chart'
      path: '/superadmin/org-chart'
      fullPath: '/superadmin/org-chart'
      preLoaderRoute: typeof SuperadminCorehcmOrgChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_employeerecords/employees': {
      id: '/superadmin/_employeerecords/employees'
      path: '/superadmin/employees'
      fullPath: '/superadmin/employees'
      preLoaderRoute: typeof SuperadminEmployeerecordsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_essmanagement/ess': {
      id: '/superadmin/_essmanagement/ess'
      path: '/superadmin/ess'
      fullPath: '/superadmin/ess'
      preLoaderRoute: typeof SuperadminEssmanagementEssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_newhireonboarding/onboarding': {
      id: '/superadmin/_newhireonboarding/onboarding'
      path: '/superadmin/onboarding'
      fullPath: '/superadmin/onboarding'
      preLoaderRoute: typeof SuperadminNewhireonboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_profilepage/profile': {
      id: '/superadmin/_profilepage/profile'
      path: '/superadmin/profile'
      fullPath: '/superadmin/profile'
      preLoaderRoute: typeof SuperadminProfilepageProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_recruitmentmanagement/recruitment': {
      id: '/superadmin/_recruitmentmanagement/recruitment'
      path: '/superadmin/recruitment'
      fullPath: '/superadmin/recruitment'
      preLoaderRoute: typeof SuperadminRecruitmentmanagementRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_settings/chatbot': {
      id: '/superadmin/_settings/chatbot'
      path: '/superadmin/chatbot'
      fullPath: '/superadmin/chatbot'
      preLoaderRoute: typeof SuperadminSettingsChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_settings/settings': {
      id: '/superadmin/_settings/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_usermanagement/users': {
      id: '/superadmin/_usermanagement/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsermanagementUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingContactRoute: LandingContactRoute,
  LandingFaqRoute: LandingFaqRoute,
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  LoginLoginRoute: LoginLoginRoute,
  LoginOtpRoute: LoginOtpRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  EmployeeAiRoute: EmployeeAiRoute,
  LandingIndexRoute: LandingIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  LandingJobsJobIdRoute: LandingJobsJobIdRoute,
  AdminApplicantManagementApplicantsRoute:
    AdminApplicantManagementApplicantsRoute,
  AdminCorehcmDeptPosRoute: AdminCorehcmDeptPosRoute,
  AdminCorehcmHcmRoute: AdminCorehcmHcmRoute,
  AdminCorehcmOrgChartRoute: AdminCorehcmOrgChartRoute,
  AdminEmployeerecordsEmployeesRoute: AdminEmployeerecordsEmployeesRoute,
  AdminEssmanagementEssRoute: AdminEssmanagementEssRoute,
  AdminNewhireonboardingOnboardingRoute: AdminNewhireonboardingOnboardingRoute,
  AdminProfilepageProfileRoute: AdminProfilepageProfileRoute,
  AdminRecruitmentmanagementRecruitmentRoute:
    AdminRecruitmentmanagementRecruitmentRoute,
  AdminSettingsChatbotRoute: AdminSettingsChatbotRoute,
  AdminSettingsSettingsRoute: AdminSettingsSettingsRoute,
  EmployeeEssmanagementEssRoute: EmployeeEssmanagementEssRoute,
  EmployeeNewhireonboardingOnboardingRoute:
    EmployeeNewhireonboardingOnboardingRoute,
  EmployeeProfilepageProfileRoute: EmployeeProfilepageProfileRoute,
  EmployeeSettingsSettingsRoute: EmployeeSettingsSettingsRoute,
  SuperadminApplicantManagementApplicantsRoute:
    SuperadminApplicantManagementApplicantsRoute,
  SuperadminAuditlogsAuditRoute: SuperadminAuditlogsAuditRoute,
  SuperadminCorehcmDeptPosRoute: SuperadminCorehcmDeptPosRoute,
  SuperadminCorehcmHcmRoute: SuperadminCorehcmHcmRoute,
  SuperadminCorehcmOrgChartRoute: SuperadminCorehcmOrgChartRoute,
  SuperadminEmployeerecordsEmployeesRoute:
    SuperadminEmployeerecordsEmployeesRoute,
  SuperadminEssmanagementEssRoute: SuperadminEssmanagementEssRoute,
  SuperadminNewhireonboardingOnboardingRoute:
    SuperadminNewhireonboardingOnboardingRoute,
  SuperadminProfilepageProfileRoute: SuperadminProfilepageProfileRoute,
  SuperadminRecruitmentmanagementRecruitmentRoute:
    SuperadminRecruitmentmanagementRecruitmentRoute,
  SuperadminSettingsChatbotRoute: SuperadminSettingsChatbotRoute,
  SuperadminSettingsSettingsRoute: SuperadminSettingsSettingsRoute,
  SuperadminUsermanagementUsersRoute: SuperadminUsermanagementUsersRoute,
  LandingJobsIndexRoute: LandingJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
