<?php

namespace Modules\ApplicantManagement\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\ApplicantManagement\Models\ScreeningReferenceData;

/**
 * Seeds screening_reference_data from the same values as the NLP service
 * bundled seed JSON (app/data/*.json), making the database the manageable
 * source of truth for skills, job roles, certifications and aliases.
 */
class ScreeningReferenceDataSeeder extends Seeder
{
    public function run(): void
    {
        $seed = [            'skill' => [
                'Attention to Detail' => ['attention to detail', 'detail oriented', 'detail-oriented'],
                'Auditing and Compliance' => ['internal auditing', 'corrective action monitoring', 'restaurant compliance', 'compliance monitoring', 'quality audit', 'compliance auditing', 'safety audit'],
                'Banquet Service' => ['banquet service', 'banquet operations', 'function service', 'banquet coordination'],
                'Bar Operations' => ['bar operations', 'beverage service', 'drink preparation', 'cocktail service', 'bar setup', 'bar station management'],
                'Barista Operations' => ['barista operations', 'barista', 'cafe service', 'coffee shop operations'],
                'Beverage Operations Supervision' => ['beverage operations supervision'],
                'Beverage Quality Standards' => ['beverage quality standards'],
                'Booking Coordination & Confirmation' => ['booking coordination & confirmation', 'booking coordination and confirmation'],
                'Budget & Supply Cost Awareness' => ['budget & supply cost awareness', 'budget and supply cost awareness'],
                'CRM and Loyalty Management' => ['crm systems', 'customer feedback analysis', 'customer retention', 'loyalty program coordination', 'relationship management', 'guest preference management'],
                'Cake Decoration' => ['cake decoration', 'cake decorating', 'cake design'],
                'Cash Handling' => ['cash handling', 'cashiering', 'billing', 'funds handling', 'cash reconciliation', 'cash drawer reconciliation'],
                'Channel Management' => ['channel management', 'ota & distribution channel coordination', 'distribution channel coordination', 'channel manager', 'reservation auditing', 'group & fit booking processing', 'ota coordination'],
                'Check-in / Check-out' => ['check-in / check-out', 'check in check out', 'check-in', 'check-out', 'arrival and departure handling'],
                'Chemical Safety' => ['chemical safety', 'cleaning chemical handling'],
                'Cleaning Standards & SOPs' => ['cleaning standards & sops', 'cleaning standards and sops'],
                'Coffee Preparation' => ['coffee preparation', 'coffee making', 'espresso making', 'espresso extraction', 'latte art', 'coffee brewing', 'coffee craft'],
                'Communication' => ['communication', 'communication skills', 'verbal communication', 'written communication', 'professional communication'],
                'Complaint Handling' => ['complaint handling', 'complaint resolution', 'guest complaint management', 'service recovery', 'guest recovery'],
                'Concierge Services' => ['concierge services', 'concierge', 'vip guest assistance', 'local area knowledge', 'area knowledge', 'transportation coordination', 'restaurant & activity reservations', 'restaurant reservations', 'activity reservations'],
                'Confidentiality' => ['confidentiality', 'data privacy', 'records confidentiality'],
                'Cost Accounting' => ['basic cost accounting', 'cost accounting', 'materials control software', 'materials control', 'marketman', 'supplier delivery verification'],
                'Cost Reporting' => ['cost reporting', 'cost control', 'f&b cost control', 'variance analysis', 'cost monitoring', 'waste tracking', 'waste reduction', 'spoilage tracking'],
                'Cost Tracking' => ['cost tracking'],
                'Cross-Department Coordination' => ['cross-department coordination'],
                'Culinary Operations' => ['menu preparation', 'kitchen operations', 'prep schedules', 'culinary preparation', 'station preparation', 'line preparation'],
                'Customer Service' => ['customer service', 'guest service', 'customer assistance', 'client service', 'customer care'],
                'Daily Sales Reporting' => ['daily sales reporting', 'daily sales reports', 'financial reporting', 'sales reports'],
                'Delivery Monitoring' => ['delivery monitoring'],
                'Event Coordination' => ['event coordination', 'events coordination', 'event planning', 'event logistics', 'event setup', 'function coordination'],
                'Facility Maintenance' => ['facility maintenance', 'maintenance support', 'electrical installation', 'plumbing basics', 'preventive maintenance', 'equipment maintenance', 'basic maintenance', 'building maintenance', 'repairs'],
                'Fine Dining Service' => ['fine dining service', 'fine-dining service', 'fine dining', 'fine-dining', 'guest greeting', 'table management', 'dining room coordination'],
                'Food Safety' => ['food safety', 'food safety compliance', 'food hygiene', 'sanitation', 'food sanitation', 'sanitation standards', 'food handling'],
                'Front Office Operations' => ['front office', 'front office operations', 'front desk', 'reception operations', 'hotel front office', 'front desk operations', 'front office procedures'],
                'Guest Activities Coordination' => ['guest activities coordination'],
                'Guest Feedback Management' => ['guest feedback management'],
                'Guest Relations' => ['guest relations', 'guest relations management', 'guest engagement', 'client relations'],
                'HACCP' => ['haccp', 'haccp compliance', 'food safety management', 'haccp protocols'],
                'Hot Kitchen' => ['hot kitchen', 'hot line', 'line cooking', 'grill station', 'saute station', 'kitchen operations', 'food preparation'],
                'Hotel Operations' => ['hotel operations', 'property operations'],
                'Housekeeping Operations' => ['housekeeping', 'housekeeping operations', 'housekeeping procedures', 'housekeeping management'],
                'Housekeeping and Room Inspection' => ['room inspection', 'sanitation protocols', 'guestroom inspection', 'housekeeping standards', 'cleaning inspection'],
                'Inventory Control' => ['inventory control', 'inventory management', 'stock control', 'stocktaking', 'inventory checks', 'inventory support', 'stock monitoring', 'par-level tracking'],
                'Inventory Counting' => ['inventory counting', 'physical inventory counting', 'perpetual inventory', 'stock reconciliation'],
                'Knife Skills' => ['knife skills', 'knife handling'],
                'Laundry Operations and Quality Control' => ['laundry quality control', 'uniform management', 'linen inspection', 'equipment monitoring', 'laundry supervision'],
                'Linen & Amenity Coordination' => ['linen & amenity coordination', 'linen and amenity coordination'],
                'Linen Handling' => ['linen handling', 'linen management', 'laundry operations', 'laundry management'],
                'MS Office' => ['ms office', 'microsoft office', 'ms word', 'ms excel', 'excel', 'word processing', 'spreadsheets', 'office suite'],
                'Menu Knowledge & Pairing' => ['menu knowledge & pairing', 'menu knowledge and pairing'],
                'Mise en Place' => ['mise en place', 'mise-en-place', 'station setup', 'prep lists'],
                'Mixology' => ['mixology', 'cocktail preparation', 'cocktail craft', 'drink mixing', 'beverage preparation', 'bar operations', 'beverage service'],
                'Night Audit Procedures' => ['night audit procedures', 'night audit', 'night auditing', 'daily audit', 'end-of-day reporting'],
                'OTA Extranet Management' => ['ota extranet management'],
                'Operational Planning' => ['operational planning'],
                'Order Taking' => ['order taking', 'taking orders', 'order processing'],
                'POS Systems' => ['pos systems', 'pos', 'point of sale', 'point of sale systems', 'micros', 'micros pos', 'toast pos', 'pos operation', 'pos system operation'],
                'Pastry and Baking' => ['pastry', 'baking', 'pastry arts', 'dessert preparation', 'breads and pastries', 'pastry preparation', 'basic baking', 'bread production'],
                'Payment Processing' => ['payment processing', 'processing payments', 'credit card processing'],
                'Payroll Support' => ['payroll support', 'payroll processing', 'payroll assistance'],
                'Plating' => ['plating', 'food plating', 'plate presentation', 'presentation', 'dessert plating'],
                'Problem Resolution' => ['problem resolution'],
                'Problem Solving' => ['problem solving', 'problem-solving', 'troubleshooting'],
                'Procurement Support' => ['procurement', 'purchasing', 'purchase order processing', 'purchase orders', 'purchase order documentation', 'vendor coordination', 'supplier coordination', 'receiving & inspection'],
                'Property Management Systems' => ['opera pms', 'opera', 'property management system', 'pms systems', 'pms', 'opera cloud', 'ids next', 'siteminder'],
                'Public Area Cleaning' => ['public area cleaning', 'public area maintenance'],
                'Quality Assurance' => ['quality assurance', 'food quality control', 'qa inspections', 'internal audit', 'compliance monitoring'],
                'Records Documentation' => ['documentation', 'records management', 'file management', '201 files', 'inventory documentation'],
                'Recreation Management' => ['recreation equipment management', 'guest activities supervision', 'seasonal program development', 'vendor & entertainment coordination', 'activities supervision', 'resort recreation'],
                'Recreation Program Planning' => ['recreation program planning', 'guest recreation', 'activity scheduling', 'activity facilitation', 'leisure coordination'],
                'Recreation Safety Awareness' => ['recreation safety awareness'],
                'Recruitment Support' => ['recruitment', 'recruitment support', 'sourcing and screening'],
                'Reservation Reporting & Forecasting' => ['reservation reporting & forecasting', 'reservation reporting and forecasting'],
                'Reservations' => ['reservations', 'reservation management', 'booking management', 'reservation support', 'reservation updates', 'room inventory', 'ota coordination'],
                'Resort Accommodation Services' => ['resort accommodation services'],
                'Responsible Alcohol Service' => ['responsible alcohol service', 'responsible service of alcohol', 'alcohol awareness'],
                'Restaurant Operations Management' => ['restaurant operations management', 'restaurant operations', 'inventory monitoring & ordering', 'service quality monitoring', 'f&b operations', 'food & beverage management'],
                'Revenue Management Support' => ['revenue management support', 'revenue management', 'rate parity', 'occupancy forecasting', 'rate monitoring'],
                'Room Status Coordination' => ['room status coordination'],
                'Room Turnover' => ['room turnover', 'room cleaning', 'guestroom cleaning'],
                'Safety Compliance' => ['safety compliance', 'workplace safety', 'safety procedures', 'occupational safety', 'safety protocols'],
                'Scheduling' => ['scheduling', 'shift scheduling', 'staff scheduling', 'kitchen scheduling'],
                'Spa Reception' => ['spa reception', 'spa operations', 'wellness reception'],
                'Staff Training' => ['staff training', 'team training', 'new hire training', 'staff coaching', 'training & onboarding'],
                'Table Management' => ['table management', 'seating management', 'table turnover', 'hostess duties'],
                'Table Service' => ['table service', 'food service', 'service sequence', 'dining room service', 'table setting'],
                'Team Leadership' => ['team leadership', 'staff supervision', 'team supervision', 'leading teams', 'shift supervision', 'floor supervision'],
                'Teamwork' => ['teamwork', 'team collaboration', 'working with others'],
                'Technical and Plumbing Maintenance' => ['basic plumbing repair', 'plumbing repair', 'emergency repair response', 'equipment inspection', 'maintenance supply inventory', 'electrical repair', 'plumbing maintenance'],
                'Telephone Etiquette' => ['telephone etiquette', 'phone etiquette', 'call handling', 'booking correspondence'],
                'Time Management' => ['time management', 'prioritization', 'multitasking'],
                'Tourism Services' => ['tourism services'],
                'Training Program Development' => ['training program development'],
                'Upselling' => ['upselling', 'upsell techniques', 'suggestive selling', 'cross-selling', 'sales & upselling'],
            ],
            'job_role' => [
                'Accounts Assistant' => ['accounts assistant', 'accounting assistant', 'finance assistant', 'bookkeeper'],
                'Banquet Operations Supervisor' => ['banquet operations supervisor', 'banquet supervisor', 'banquet operations manager', 'banquet manager'],
                'Banquet Service Team Leader' => ['banquet service team leader', 'banquet team leader', 'banquet service supervisor', 'banquet team supervisor'],
                'Bar Operations Supervisor' => ['bar operations supervisor', 'restaurant bar operations supervisor', 'bar supervisor', 'bar manager', 'bar lead', 'bar team leader'],
                'Barista' => ['barista', 'coffee shop staff', 'cafe barista', 'coffee attendant'],
                'Bartender' => ['bartender', 'bar tender', 'barman', 'barkeep', 'mixologist'],
                'Beverage Service Specialist' => ['beverage service specialist', 'restaurant beverage service specialist', 'beverage specialist', 'bar specialist', 'beverage attendant'],
                'Catering Operations Coordinator' => ['catering operations coordinator', 'catering coordinator', 'banquet catering coordinator', 'catering operations'],
                'Catering and Banquet Sales Coordinator' => ['catering and banquet sales coordinator', 'catering sales coordinator', 'banquet sales coordinator', 'catering coordinator', 'banquet sales assistant'],
                'Chef' => ['chef', 'sous chef', 'head chef', 'executive chef', 'chef de partie', 'executive sous chef', 'banquet chef', 'demi chef'],
                'Concierge' => ['concierge', 'hotel concierge', 'bell captain', 'bellman'],
                'Culinary Production Coordinator' => ['culinary production coordinator', 'kitchen production coordinator', 'culinary coordinator', 'culinary production'],
                'Dining Service Supervisor' => ['dining service supervisor', 'restaurant service supervisor', 'dining supervisor', 'service supervisor dining', 'dining room supervisor'],
                'Events Catering Supervisor' => ['events catering supervisor', 'catering supervisor', 'event catering coordinator', 'banquet catering supervisor'],
                'Events Coordinator' => ['sales and events coordinator', 'hotel sales and events coordinator', 'events coordinator', 'banquet coordinator', 'event coordinator', 'catering assistant', 'events and catering assistant', 'banquet sales assistant', 'banquet server'],
                'Executive Housekeeper' => ['executive housekeeper', 'housekeeping manager', 'housekeeping executive', 'head housekeeper'],
                'Food Beverage Events Supervisor' => ['food beverage events supervisor', 'food and beverage events supervisor', 'f&b events supervisor', 'food beverage supervisor'],
                'Food Production Supervisor' => ['food production supervisor', 'kitchen production supervisor', 'food production coordinator', 'culinary production supervisor'],
                'Food and Beverage Manager' => ['food and beverage manager', 'f&b manager', 'restaurant manager', 'food & beverage manager'],
                'Front Desk Associate' => ['front desk associate', 'front office associate', 'front desk representative', 'guest service representative', 'front desk clerk', 'front office intern'],
                'Front Desk Receptionist' => ['front desk agent', 'front desk officer', 'front desk receptionist', 'front desk staff', 'front office associate', 'guest service agent', 'receptionist'],
                'Front Office Manager' => ['front office manager', 'front desk manager', 'front office lead', 'guest services manager'],
                'General Manager' => ['general manager', 'gm', 'property manager'],
                'Guest Booking Team Leader' => ['guest booking team leader', 'booking team leader', 'reservations team leader', 'booking services team leader'],
                'Guest Experience Coordinator' => ['guest experience coordinator', 'guest experience and loyalty coordinator', 'hotel guest experience and loyalty coordinator', 'loyalty coordinator'],
                'Guest Experience Officer' => ['guest experience officer', 'guest experience coordinator', 'guest experience specialist', 'gxo', 'guest experience officer hotel'],
                'Guest Relations Officer' => ['gro', 'guest relations coordinator', 'guest relations officer', 'guest service officer', 'guest relations associate'],
                'HR Assistant' => ['hr assistant', 'human resource assistant', 'human resources assistant', 'hr staff', 'recruitment assistant'],
                'HR Manager' => ['hr manager', 'human resources manager', 'hr administration manager'],
                'Hospitality Client Relations Team Leader' => ['hospitality client relations team leader', 'client relations team leader', 'client relations supervisor', 'hospitality client relations supervisor'],
                'Hospitality Corporate Sales Coordinator' => ['hospitality corporate sales coordinator', 'corporate sales coordinator', 'corporate sales officer', 'sales coordinator corporate', 'hospitality sales coordinator'],
                'Hospitality Facilities Team Leader' => ['hospitality facilities team leader', 'facilities team leader', 'facilities supervisor', 'hospitality facilities supervisor'],
                'Hospitality Kitchen Coordinator' => ['hospitality kitchen coordinator', 'kitchen coordinator', 'hospitality kitchen', 'culinary coordinator'],
                'Hospitality Maintenance Coordinator' => ['hospitality maintenance coordinator', 'maintenance coordinator', 'facilities maintenance coordinator', 'hospitality maintenance supervisor'],
                'Hospitality Reservations Specialist' => ['hospitality reservations specialist', 'reservations specialist', 'hospitality reservations officer', 'reservations officer hospitality'],
                'Hostess' => ['hostess', 'food host', 'restaurant host', 'fine dining restaurant host', 'host'],
                'Hotel Banquet Coordinator' => ['hotel banquet coordinator', 'banquet coordinator', 'hotel banquet', 'banquet events coordinator'],
                'Hotel Booking Services Officer' => ['hotel booking services officer', 'booking services officer', 'hotel booking officer', 'booking officer hotel'],
                'Hotel Business Development Coordinator' => ['hotel business development coordinator', 'business development coordinator', 'business development officer', 'hotel sales development coordinator', 'business development coordinator hotel'],
                'Hotel Engineering Operations Assistant' => ['hotel engineering operations assistant', 'engineering operations assistant', 'hotel engineering assistant', 'engineering assistant hotel'],
                'Hotel Events Sales Officer' => ['hotel events sales officer', 'events sales officer', 'event sales officer', 'hotel sales officer', 'events officer hotel'],
                'Hotel Facilities Supervisor' => ['hotel facilities supervisor', 'facilities supervisor', 'property maintenance supervisor', 'hotel facilities manager'],
                'Hotel Front Office Supervisor' => ['hotel front office supervisor', 'front office supervisor', 'front desk supervisor', 'hotel front office manager', 'front office lead'],
                'Hotel Night Auditor' => ['night auditor', 'hotel night auditor', 'night audit associate', 'night audit supervisor'],
                'Hotel Property Maintenance Supervisor' => ['hotel property maintenance supervisor', 'property maintenance supervisor', 'maintenance supervisor hotel', 'property maintenance manager'],
                'Hotel Reservations Manager' => ['hotel reservations manager', 'reservations manager', 'hotel reservations supervisor', 'reservations manager hotel'],
                'Hotel Reservations Sales Coordinator' => ['hotel reservations sales coordinator', 'reservations sales coordinator', 'hotel reservations sales', 'reservations coordinator sales'],
                'Hotel Reservations Supervisor' => ['hotel reservations supervisor', 'reservations supervisor', 'hotel reservations manager', 'reservations manager hotel'],
                'Hotel Revenue Analyst' => ['hotel revenue analyst', 'revenue analyst', 'revenue management analyst', 'hotel revenue management analyst', 'pricing analyst', 'revenue analyst hotel'],
                'Hotel Sales and Events Supervisor' => ['hotel sales and events supervisor', 'sales and events supervisor', 'hotel sales supervisor', 'sales events supervisor', 'hotel sales and events coordinator'],
                'Housekeeping Attendant' => ['housekeeping attendant', 'room attendant', 'housekeeper', 'chambermaid', 'roomboy', 'public area attendant'],
                'Housekeeping Supervisor' => ['housekeeping supervisor', 'hotel housekeeping supervisor', 'floor housekeeper', 'executive housekeeper'],
                'Inventory Supervisor' => ['inventory supervisor', 'cost control supervisor', 'restaurant inventory and cost control supervisor', 'inventory and cost control supervisor', 'stock controller', 'inventory clerk', 'restaurant stock controller'],
                'Kitchen Helper' => ['kitchen helper', 'dishwasher', 'kitchen aide', 'steward', 'kitchen steward', 'kitchen staff'],
                'Kitchen Operations Supervisor' => ['kitchen operations supervisor', 'culinary operations supervisor', 'kitchen supervisor operations', 'kitchen operations manager'],
                'Kitchen Supervisor' => ['kitchen supervisor', 'restaurant kitchen supervisor', 'culinary supervisor', 'chef supervisor'],
                'Laundry Attendant' => ['laundry attendant', 'laundry staff'],
                'Laundry Supervisor' => ['laundry supervisor', 'hotel laundry supervisor', 'laundry team leader'],
                'Line Cook' => ['line cook', 'cook', 'station cook', 'hot kitchen cook', 'commis chef', 'kitchen cook', 'senior line cook'],
                'Maintenance Technician' => ['maintenance technician', 'hotel maintenance technician', 'maintenance staff', 'handyman', 'building maintenance staff', 'facilities assistant'],
                'Pastry Chef' => ['pastry chef', 'baker', 'pastry cook', 'baker chef'],
                'Pastry and Bakery Assistant' => ['pastry assistant', 'bakery assistant', 'bakery trainee', 'pastry cook'],
                'Purchasing Coordinator' => ['purchasing coordinator', 'procurement coordinator', 'hotel purchasing and procurement coordinator', 'purchasing and inventory assistant', 'purchasing assistant', 'procurement assistant'],
                'Quality Assurance Officer' => ['quality assurance officer', 'restaurant quality assurance and food safety officer', 'food safety officer', 'qa officer', 'qa and food safety officer', 'qa assistant', 'restaurant compliance officer'],
                'Recreation Supervisor' => ['recreation supervisor', 'resort recreation and activities supervisor', 'activities supervisor', 'recreation coordinator', 'activities coordinator', 'hotel recreation and activities coordinator', 'resort activities assistant'],
                'Reservations Booking Coordinator' => ['reservations booking coordinator', 'booking coordinator', 'reservations coordinator', 'hotel booking coordinator'],
                'Reservations Coordinator' => ['reservations coordinator', 'hotel reservations and distribution coordinator', 'reservations and distribution coordinator', 'reservations officer', 'reservations assistant', 'hotel reservations assistant', 'hotel reservations officer'],
                'Reservations Manager' => ['reservations manager', 'reservation manager', 'booking manager'],
                'Resort Guest Experience Manager' => ['resort guest experience manager', 'guest experience manager', 'guest experience supervisor', 'resort guest relations manager'],
                'Resort Housekeeping Operations Manager' => ['resort housekeeping operations manager', 'housekeeping operations manager', 'resort housekeeping manager', 'housekeeping manager', 'housekeeping operations supervisor', 'resort housekeeping operations'],
                'Resort Operations Manager' => ['resort operations manager', 'hotel operations manager', 'resort manager', 'operations manager resort'],
                'Resort Property Operations Coordinator' => ['resort property operations coordinator', 'property operations coordinator', 'property coordinator', 'resort operations coordinator'],
                'Resort Recreation and Activities Manager' => ['resort recreation and activities manager', 'recreation and activities manager', 'resort recreation manager', 'activities manager', 'recreation supervisor resort'],
                'Restaurant Beverage Supervisor' => ['restaurant beverage supervisor', 'beverage supervisor', 'bar supervisor', 'beverage service supervisor', 'restaurant bar supervisor'],
                'Restaurant Cashier' => ['restaurant cashier', 'cashier', 'cashier and customer service associate', 'dining cashier', 'customer service associate'],
                'Restaurant Culinary Operations Officer' => ['restaurant culinary operations officer', 'culinary operations officer', 'restaurant culinary officer', 'culinary officer restaurant'],
                'Restaurant Customer Experience Coordinator' => ['restaurant customer experience coordinator', 'customer experience coordinator', 'cx coordinator', 'guest experience coordinator restaurant', 'customer experience coordinator restaurant'],
                'Restaurant Events and Banquet Coordinator' => ['restaurant events and banquet coordinator', 'events and banquet coordinator', 'restaurant events coordinator', 'banquet coordinator', 'events coordinator restaurant'],
                'Restaurant Guest Relations Supervisor' => ['restaurant guest relations supervisor', 'guest relations supervisor', 'restaurant guest relations coordinator', 'guest relations supervisor restaurant'],
                'Restaurant Kitchen Team Leader' => ['restaurant kitchen team leader', 'kitchen team leader', 'restaurant kitchen team', 'kitchen supervisor team leader'],
                'Restaurant Procurement and Purchasing Coordinator' => ['restaurant procurement and purchasing coordinator', 'procurement and purchasing coordinator', 'restaurant procurement coordinator', 'purchasing coordinator', 'procurement coordinator'],
                'Restaurant Relations Coordinator' => ['restaurant relations coordinator', 'guest relations coordinator', 'relations coordinator', 'restaurant guest relations coordinator'],
                'Restaurant Server' => ['restaurant server', 'waiter', 'waitress', 'food server', 'server', 'food and beverage attendant', 'f&b attendant', 'service crew', 'restaurant crew member'],
                'Restaurant Service Team Leader' => ['restaurant service team leader', 'service team leader', 'restaurant team leader', 'service supervisor', 'restaurant service supervisor'],
                'Restaurant Supervisor' => ['restaurant supervisor', 'floor supervisor', 'service supervisor', 'senior server lead', 'food and beverage supervisor', 'f&b supervisor'],
                'Revenue Management Assistant' => ['revenue management assistant', 'hotel revenue management assistant', 'revenue assistant', 'pricing assistant'],
                'Spa Receptionist' => ['spa receptionist', 'hotel spa and wellness receptionist', 'wellness receptionist', 'spa front desk', 'spa and wellness receptionist'],
                'Supervisor' => ['supervisor', 'shift supervisor', 'team leader'],
            ],
            'certification' => [
                'Advanced Negotiation Skills for Sales Professionals, 2022' => ['advanced negotiation skills for sales professionals, 2022', 'advanced negotiation skills for sales professionals,'],
                'Banquet and Event Service Excellence Training - Philippine Hotel Owners Association (2022)' => ['banquet and event service excellence training - philippine hotel owners association (2022)', 'banquet and event service excellence training - philippine hotel owners association', 'banquet and event service excellence training'],
                'Barista NC II' => ['barista nc ii', 'tesda barista nc ii', 'coffee academy certificate'],
                'Barista and Coffee Craft Training' => ['barista and coffee craft training', 'barista & coffee craft training', 'coffee craft training', 'barista training'],
                'Basic Bookkeeping and Accounting Training' => ['basic bookkeeping and accounting training', 'basic bookkeeping training', 'basic accounting for non-accountants', 'bookkeeping training', 'basic cost accounting training'],
                'Basic Electrical Systems Maintenance Certificate - TESDA (2013)' => ['basic electrical systems maintenance certificate - tesda (2013)', 'basic electrical systems maintenance certificate - tesda', 'basic electrical systems maintenance certificate'],
                'Basic First Aid and CPR Certification' => ['basic first aid and cpr certification', 'basic first aid and cpr', 'basic first aid training', 'basic occupational first aid', 'first aid and cpr', 'basic life support and first aid certification', 'basic first aid and safety training', 'first aid certificate', 'first aid training certificate', 'standard first aid', 'basic first aid'],
                'Basic Occupational Safety and Health Training' => ['basic occupational safety and health training', 'occupational safety and health training', 'occupational safety and health awareness training', 'workplace safety training', 'osh training', 'bosh training'],
                'Business Development Fundamentals for Hospitality, 2024' => ['business development fundamentals for hospitality, 2024', 'business development fundamentals for hospitality,'],
                'Cash Handling and POS Training' => ['cash handling and pos training', 'cash handling & pos training', 'cash handling and pos system operation'],
                'Catering Sales Fundamentals Training, 2023' => ['catering sales fundamentals training, 2023', 'catering sales fundamentals training,'],
                'Client Relations Leadership Workshop, 2024' => ['client relations leadership workshop, 2024', 'client relations leadership workshop,'],
                'Culinary Diploma' => ['culinary diploma', 'diploma in culinary arts', 'culinary arts diploma', 'culinary arts'],
                'Culinary Production Training, 2023' => ['culinary production training, 2023', 'culinary production training,'],
                'Customer Service Excellence Training' => ['customer service excellence training', 'customer service excellence certification', 'customer service excellence workshop', 'customer service training', 'hospitality guest relations training', 'customer service and guest relations training'],
                'Data Analysis Fundamentals' => ['data analysis fundamentals', 'data analysis fundamentals — coursera', 'hospitality data analytics'],
                'Data Privacy and Information Security Training' => ['data privacy and guest information awareness', 'data privacy awareness', 'guest data confidentiality training'],
                'Driver\'s License' => ['driver\'s license', 'drivers license', 'professional driver license', 'non-professional driver license'],
                'Event Management Training' => ['events management training', 'event management training', 'event management fundamentals', 'events and recreation management training', 'event facilitation training certificate', 'event facilitation training'],
                'Facilities Management Training - Philippine Society of Ventilating, Air-Conditioning and Refrigerating Engineers (2020)' => ['facilities management training - philippine society of ventilating, air-conditioning and refrigerating engineers (2020)', 'facilities management training - philippine society of ventilating, air-conditioning and refrigerating engineers', 'facilities management training - philippine society of ventilating, air'],
                'Fine-Dining Service Training' => ['fine-dining service training', 'fine dining service training', 'fine dining service training — peninsula academy', 'upscale dining service training'],
                'Food Handler Certificate' => ['food handler certificate', 'food handler\'s certificate', 'food handlers certificate', 'food safety certificate', 'food handler card'],
                'Food Safety Awareness Certification, 2021' => ['food safety awareness certification, 2021', 'food safety awareness certification,'],
                'Food Safety and Hygiene Certification' => ['food safety and hygiene certification', 'food safety and hygiene training', 'food safety and sanitation training', 'food safety supervisor certification', 'food safety supervisor certification (haccp)', 'food safety & hygiene certification', 'food safety training', 'food safety certification', 'restaurant operations and food safety orientation', 'hygiene and sanitation training'],
                'Food and Beverage Cost Control Training' => ['food and beverage cost control training', 'f&b cost control training', 'cost control training'],
                'Front Office & Reservation Systems Training, 2022' => ['front office & reservation systems training, 2022', 'front office & reservation systems training,'],
                'Front Office Team Leadership Workshop, 2024' => ['front office team leadership workshop, 2024', 'front office team leadership workshop,'],
                'Guest Communication Standards Workshop, 2021' => ['guest communication standards workshop, 2021', 'guest communication standards workshop,'],
                'Guest Relations and Customer Experience Training' => ['guest relations and customer experience training', 'guest relations and customer experience training - philippine hotel and restaurant association', 'crm fundamentals training', 'customer relationship management training', 'professional communication and etiquette training', 'professional etiquette training', 'business communication workshop'],
                'HACCP Awareness Training' => ['haccp awareness training', 'haccp certification', 'haccp training', 'food safety (haccp)', 'food safety supervisor certification (haccp)', 'haccp compliance training'],
                'Hospitality Leadership Training - Hotel and Restaurant Association of the Philippines (2020)' => ['hospitality leadership training - hotel and restaurant association of the philippines (2020)', 'hospitality leadership training - hotel and restaurant association of the philippines', 'hospitality leadership training'],
                'Hospitality Sales Support Fundamentals, 2022' => ['hospitality sales support fundamentals, 2022', 'hospitality sales support fundamentals,'],
                'Hospitality Sales Training, Philippine Hotel Sales Association, 2021' => ['hospitality sales training, philippine hotel sales association, 2021', 'hospitality sales training, philippine hotel sales association,'],
                'Hotel Front Office Operations Training' => ['hotel front office operations training', 'front office operations training', 'front office training', 'hospitality service training (front office operations)', 'hotel front office training'],
                'Hotel Reservation Systems Training – Opera PMS Certification, 2021' => ['hotel reservation systems training – opera pms certification, 2021', 'hotel reservation systems training – opera pms certification,'],
                'Hotel Revenue Management Training' => ['hotel revenue management training', 'revenue management training'],
                'Housekeeping and Laundry Operations Training' => ['housekeeping and sanitation training', 'laundry operations training', 'laundry operations training — philippine hotel owners association', 'hotel housekeeping operations training'],
                'Internal Quality Audit Training' => ['internal quality audit training', 'internal quality audit training — bureau veritas philippines', 'quality audit training', 'iso internal audit training'],
                'Inventory Management Training' => ['inventory management training', 'inventory management training certificate', 'inventory control training'],
                'Kitchen Inventory & Cost Control Basics, 2023' => ['kitchen inventory & cost control basics, 2023', 'kitchen inventory & cost control basics,'],
                'Kitchen Operations Training, Philippine Culinary Federation, 2022' => ['kitchen operations training, philippine culinary federation, 2022', 'kitchen operations training, philippine culinary federation,'],
                'Microsoft Excel Certification' => ['microsoft excel certification', 'microsoft excel advanced certification', 'advanced microsoft excel for business analytics', 'microsoft excel for financial reporting', 'microsoft excel training', 'microsoft excel training (intermediate)', 'microsoft excel intermediate certification'],
                'Opera PMS Training' => ['opera pms training', 'opera cloud pms reservations training certificate', 'opera pms reservation system training', 'hotel reservation system fundamentals', 'siteminder channel manager fundamentals'],
                'Pastry and Dessert Plating Training' => ['cake decoration and dessert plating training', 'advanced pastry training', 'advanced pastry training — le cordon bleu manila', 'dessert plating training'],
                'Procurement and Supply Chain Fundamentals Training' => ['procurement and supply chain fundamentals training', 'basic purchasing and procurement training', 'basic purchasing and vendor management training', 'purchasing and supply management training'],
                'Recreation and Leisure Management Training' => ['recreation and leisure management training', 'recreation management training', 'activity facilitation and event coordination training', 'events and recreation management training', 'resort recreation management training'],
                'Reservation & Rate Management Training, 2023' => ['reservation & rate management training, 2023', 'reservation & rate management training,'],
                'Reservation & Sales Coordination Training, 2024' => ['reservation & sales coordination training, 2024', 'reservation & sales coordination training,'],
                'Reservation Documentation & Booking Systems Training, 2023' => ['reservation documentation & booking systems training, 2023', 'reservation documentation & booking systems training,'],
                'Responsible Beverage Service Training' => ['responsible beverage service training', 'responsible beverage service', 'responsible alcohol service training', 'beverage service training', 'bar operations training'],
                'Restaurant Service Standards Training, 2023' => ['restaurant service standards training, 2023', 'restaurant service standards training,'],
                'Sales and Client Relations Training, 2023' => ['sales and client relations training, 2023', 'sales and client relations training,'],
                'Service Recovery and Complaint Handling Workshop (2019)' => ['service recovery and complaint handling workshop (2019)', 'service recovery and complaint handling workshop'],
                'Spa and Wellness Service Training' => ['spa and wellness service training', 'spa reception & guest service training', 'spa reception and guest service training', 'wellness & hospitality service training', 'wellness and hospitality service training'],
                'Supervisory and Leadership Training' => ['basic supervisory skills training', 'basic supervisory skills training - hospitality skills institute', 'leadership and supervisory training', 'hospitality supervisory skills training'],
                'TESDA Bartending NC II' => ['tesda bartending nc ii', 'bartending nc ii', 'bartending nc 2', 'tesda nc ii in bartending'],
                'TESDA Bread and Pastry Production NC II' => ['bread and pastry production nc ii', 'baking nc ii', 'pastry production nc ii', 'tesda bread and pastry production nc ii', 'bread and pastry nc ii'],
                'TESDA Cookery NC II' => ['tesda cookery nc ii', 'cookery nc ii', 'tesda cookery nc 2', 'commercial cooking nc ii', 'tesda nc ii in cookery', 'tesda cookery'],
                'TESDA Electrical Installation and Maintenance NC II' => ['electrical installation and maintenance nc ii', 'tesda electrical installation and maintenance nc ii', 'electrical installation nc ii', 'electrical installation & maintenance nc ii'],
                'TESDA Food and Beverage Services NC II' => ['food and beverage services nc ii', 'f&b services nc ii', 'fb services nc ii', 'food and beverage nc ii', 'tesda food and beverage services nc ii', 'food & beverage services nc ii'],
                'TESDA Front Office NC II' => ['tesda front office nc ii', 'front office nc ii', 'front office services nc ii', 'tesda front office services nc ii'],
                'TESDA Housekeeping NC II' => ['tesda housekeeping nc ii', 'housekeeping nc ii', 'housekeeping nc 2', 'tesda nc ii in housekeeping'],
                'Team Leadership for Front Office Supervisors, 2022' => ['team leadership for front office supervisors, 2022', 'team leadership for front office supervisors,'],
                'Technical Maintenance and Plumbing Training' => ['basic plumbing training', 'plumbing maintenance training', 'facility maintenance training'],
            ],
        ];

        foreach ($seed as $type => $entries) {
            foreach ($entries as $canonical => $aliases) {
                DB::table((new ScreeningReferenceData)->getTable())->updateOrInsert([
                    'data_type' => $type,
                    'canonical_value' => $canonical,
                ], [
                    'aliases_json' => json_encode($aliases),
                    'active' => true,
                ]);
            }
        }
    }
}
